#!/bin/bash

CINEMA=$CINEMAPATH
PYTHONPATH=$CINEMA_PYTHONPATH:$PYTHONPATH

if [ "$1" == "" ]; then
    echo "Need name of Cinema database to process. Exiting ..."
    exit 0
fi

echo "--------------------------------------------------"
echo "CINEMA: creating database"
echo "--------------------------------------------------"

CDB=$1
DIRNAME=`dirname $CDB`
CDB=`basename $CDB`
INSTALL=`pwd`/install
# pull the cinema install modules @ git commit id
wget https://github.com/cinemascience/cinema_install/archive/cec4f8d5fba56d630e62307ded8a336e48b6d169.zip
unzip cec4f8d5fba56d630e62307ded8a336e48b6d169.zip
mv cinema_install-cec4f8d5fba56d630e62307ded8a336e48b6d169/cinstall .
rm -rf cinema_install-cec4f8d5fba56d630e62307ded8a336e48b6d169/ cec4f8d5fba56d630e62307ded8a336e48b6d169.zip
export PYTHONPATH=$PYTHONPATH:`pwd`

# cd to data dir to transmogrify database
pushd $DIRNAME >/dev/null
DIRNAME=`pwd`
FULLPATH=$DIRNAME/$CDB

VERBOSE=false
if [ "$VERBOSE" = true ]; then
    echo "--------------------------------------------------"
    echo "CINEMA" 
    echo "dirname : $DIRNAME"
    echo "fullpath: $FULLPATH"
    echo "cdb     : $CDB"
    echo "install : $INSTALL"
    echo "cinema  : $CINEMA"
    echo "--------------------------------------------------"
fi

# fix a bug in the ASCENT database output
sed -i 's/ //g' $CDB/data.csv


# create greyscale images
FILE=3
echo $CINEMA -d $CDB --image-grey $FILE
$CINEMA -d $CDB --image-grey $FILE 2>/dev/null
((GREYSCALE=FILE+1))

# compute several quantities
echo $CINEMA -d $CDB --image-unique $GREYSCALE
$CINEMA -d $CDB --image-unique $GREYSCALE
((GREYSCALE=GREYSCALE+1))
echo $CINEMA -d $CDB --image-entropy $GREYSCALE
$CINEMA -d $CDB --image-entropy $GREYSCALE

# fix a bug in the components
sed -i '1 s/ /_/g' $CDB/data.csv

# return to cinema_workflows
popd

# install a viewer 
$INSTALL $CDB

# clean up
rm -rf cinstall

