#!/usr/bin/env python


from cinstall.install import install 


dbs = [ 
        {  "path": "nyx.cdb", 
           "selection" : { "image_unique_count"   : [130.0, 137.0],
                           "image_shannon_entropy": [2.0, 2.5] }
        }
      ]
install.explorer( "cinstall/cinema.source",
                  ".", 
                  "explore.html",
                  dbs)


