#!/usr/bin/env python

from cinstall.install import install 
import sys


if ( len(sys.argv) == 2 ):
    print("ERROR: need 2 args (path of 2 Cinema databases)")
    print("exiting ...")
    exit(0)

dbpath1 = sys.argv[1]
dbpath2 = sys.argv[2]
print("database1: {}".format(dbpath1))
print("database2: {}".format(dbpath2))

dbs = [ 
        {  "path": dbpath1, 
           "selection" : { "image_unique_count"   : [130.0, 137.0],
                           "image_shannon_entropy": [2.0, 2.5] }
        },
        {  "path": dbpath2, 
           "selection" : { "image_unique_count"   : [600, 800],
                           "image_shannon_entropy": [2.0, 2.5] }
        }
      ]
install.explorer( "cinstall/cinema.source",
                  ".", 
                  "explore.html",
                  dbs)


