#!/bin/bash

if [ "$1" == "" ]; then
    echo "Need name of Cinema database to process. Exiting ..."
    exit 0
fi

CDB=$1

# fix a bug in the ASCENT database output
sed -i "" "s/ //g" $CDB/data.csv

# pull the cinema install modules
git clone git@github.com:cinemascience/cinema_install.git
mv cinema_install/cinstall .
rm -rf cinema_install

# create greyscale images
FILE=3
echo cinema -d $CDB --image-grey $FILE
cinema -d $CDB --image-grey $FILE 2>/dev/null
((GREYSCALE=FILE+1))

# compute several quantities
echo cinema -d $CDB --image-unique $GREYSCALE
cinema -d $CDB --image-unique $GREYSCALE
((GREYSCALE=GREYSCALE+1))
echo cinema -d $CDB --image-entropy $GREYSCALE
cinema -d $CDB --image-entropy $GREYSCALE

# fix a bug in the components
sed -i '' '1 s/ /_/g' $CDB/data.csv

# install a viewer 
./install

# clean up
rm -rf cinstall

