#!/bin/bash

CINEMA=$CINEMAPATH
PYTHONPATH=$CINEMA_PYTHONPATH:$PYTHONPATH

if [ "$1" == "" ]; then
    echo "Need name of Cinema database to process. Exiting ..."
    exit 0
fi

CDB=$1
DIRNAME=`dirname $CDB`
CDB=`basename $CDB`
INSTALL=`pwd`/install
pushd $DIRNAME >/dev/null
DIRNAME=`pwd`
FULLPATH=$DIRNAME/$CDB

VERBOSE=false
if [ "$VERBOSE" = true ]; then
    echo "dirname : $DIRNAME"
    echo "fullpath: $FULLPATH"
    echo "cdb     : $CDB"
    echo "install : $INSTALL"
    echo "cinema  : $CINEMA"
fi

# fix a bug in the ASCENT database output
sed -i 's/ //g' $CDB/data.csv

# pull the cinema install modules
# git clone git@github.com:cinemascience/cinema_install.git
git clone https://github.com/cinemascience/cinema_install.git 
mv cinema_install/cinstall .
rm -rf cinema_install

# create greyscale images
FILE=3
echo $CINEMA -d $CDB --image-grey $FILE
$CINEMA -d $CDB --image-grey $FILE 2>/dev/null
((GREYSCALE=FILE+1))

# compute several quantities
echo $CINEMA -d $CDB --image-unique $GREYSCALE
$CINEMA -d $CDB --image-unique $GREYSCALE
((GREYSCALE=GREYSCALE+1))
echo $CINEMA -d $CDB --image-entropy $GREYSCALE
$CINEMA -d $CDB --image-entropy $GREYSCALE

# fix a bug in the components
sed -i '1 s/ /_/g' $CDB/data.csv

# install a viewer 
$INSTALL $CDB

# clean up
rm -rf cinstall

# return to the original place
popd
